spring:
  application:
    name: backend

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 305289450602-euu5eo1cdj4vspj4g81ldnq6je06lhor.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1446358566365773
            client-secret: e0931417cf96ff6b023129bfe0504a86

  web:
    resources:
      static-locations:
        - "file:///C:/Room-Renting/Media/PostMedia/"
        - "file:///C:/Room-Renting/Media/MessageMedia/"
      cache:
        period: 0

  datasource:
    url: jdbc:mysql://localhost:3306/room_renting
    username: root
    password: Duyanh090@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/room_renting
      database: room_renting
      auto-index-creation: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

server:
  address: 0.0.0.0
  port: 8080